# Generated by Django 4.1.2 on 2024-03-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0003_alter_customuser_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="Try",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
            ],
        ),
    ]
