# Generated by Django 4.1.2 on 2024-03-04 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0004_try"),
    ]

    operations = [
        migrations.AlterField(
            model_name="try",
            name="image",
            field=models.ImageField(upload_to="media/videos/"),
        ),
    ]
